### ISSUE TITLE
Code cleanup and Configure ESLint to enforce rules.

### ISSUE THREAD

**Issue by carlzoo** [carlzoo/scalperr-ui#35]
Remove unused imports and variables. Debugging lines can be kept.
Change any inconsistency in spacing and variable names.

Exception:
Keep Canvas, unless ESLint rules are implemented.

**Comment by calebmchenry** [comment]
Hello, I can take this one. Let me know if you have preferences on the eslint setup. Otherwise I will just use some standard configs and prettier.

**Comment by carlzoo** [comment]
Hi @calebmchenry. Thanks for your interest in the project. I would suggest a standard setup for now and will look through your PR.
