### ISSUE TITLE
Searched results cached incorrectly

### ISSUE THREAD

**Issue by carlzoo** [carlzoo/scalperr-ui#38]
Some results from previous searches are still showing up in subsequent searches. Investigate this.

Write a test where no content from previous search results should appear in subsequent results, given that the queries are entirely different.

**Comment by conoroshea1996** [comment]
What are the steps required to repeat this bug in my local environment?

**Comment by carlzoo** [comment]
Not able to produce this at the moment - will reopen if necessary.
